### ISSUE TITLE
Sensor implements device_state_attributes.

### ISSUE THREAD

**Issue by gerritjonker** [cyberjunky/home-assistant-toon_boilerstatus#11]
Toon boiler status 1.0.9
HA core-2021.12.1

Since the December update the logfile records the following warnings:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549 
First occurred: 21:03:33 (29 occurrences) 
Last logged: 21:03:35

Entity sensor.toon_boiler_outtemp (<class 'custom_components.toon_boilerstatus.sensor.ToonBoilerStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.toon_boiler_pressure (<class 'custom_components.toon_boilerstatus.sensor.ToonBoilerStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.toon_boiler_modulation (<class 'custom_components.toon_boilerstatus.sensor.ToonBoilerStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.toon_room_temp (<class 'custom_components.toon_boilerstatus.sensor.ToonBoilerStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.toon_room_temp_setpoint (<class 'custom_components.toon_boilerstatus.sensor.ToonBoilerStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

It seems to be related to this pull request"
[https://github.com/home-assistant/core/pull/47304]

**Comment by Peklaa** [comment]
The same issue seems to have been resolved in the toon_climate component recently, see: https://github.com/cyberjunky/home-assistant-toon_climate/issues/35 
I also noticed that the toon_boilerstatus sensors are not available for display in a Statistics Graph Card, see https://www.home-assistant.io/lovelace/statistics-graph/. Would that be worth fixing as well?

**Comment by wwolkers** [comment]
pull request #12 should fix this warning.

**Comment by wwolkers** [comment]
pull request #13 should add the support for statistics graph card

**Comment by cyberjunky** [comment]
Just release 1.0.10, thanks all!

**Comment by Peklaa** [comment]
Awesome, that's super fast! Thanks Wouter and Ron! 
I installed 1.0.10 right away, restarted HA core and waited for a couple of hours for the statistics to build. The logfile warnings are gone, so that's great. However, I'm still unable to create a statistics graph card with my sensor.toon_room_temp in it. Am I doing something wrong?

**Comment by cyberjunky** [comment]
@Peklaa I fixed some stuff with a code rewrite in Release 1.0.11, can you test, and reopen if you still have an issue?

**Comment by Peklaa** [comment]
Yes, tested and 1.0.11has fixed it. Thanks again Ron!
